# Backend
backend = "glx";
vsync = true;

# Shadows (optional but recommended)
shadow = true;
shadow-radius = 12;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-opacity = 0.30;

# Rounded corners
corner-radius = 0;

rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'i3-frame'",
  "class_g = 'Polybar'",
  "class_g = 'i3bar'",
  "class_g = 'Conky'",
  "class_g = 'dmenu'"
];

# Transparency (optional)
	inactive-opacity = 0.93;
	active-opacity = 0.97;
	frame-opacity = 1.00;

# Blur (OFF by default – enable only if you want it)
blur-method = "dual_kawase"
blur-strength = 5
blur-background = true
