# Font
font_family      BlexMono Nerd Font Mono
bold_font        Auto
italic_font      Auto
bold_italic_font Auto
font_size        14.0

# Spacing (tight, archival)
adjust_line_height  4
adjust_column_width 0
window_padding_width 4

# Cursor
cursor_beam_thickness 7
cursor_underline_thickness 4.0

# No bell
enable_audio_bell no
visual_bell_duration 0.0


foreground            #fff
background            #000000
cursor                #fff
cursor_text_color     #000000
selection_foreground  #000000
selection_background  #00ff00

# Black
color0   #000000
color8   #003300

# Red
color1   #00aa00
color9   #00ff00

# Green
color2   #00ff00
color10  #66ff66

# Yellow
color3   #00cc00
color11  #99ff99

# Blue
color4   #009900
color12  #33ff33

# Magenta
color5   #00bb00
color13  #55ff55

# Cyan
color6   #00dd00
color14  #77ff77

# White
color7   #00ff00
color15  #ccffcc



# Transparency (very subtle)
background_opacity 0.97

# Performance / Old-school feel
repaint_delay 10
input_delay 0


# BEGIN_KITTY_THEME
# END_KITTY_THEME
