# Font
font_family      Hack Nerd Font
bold_font        Auto
italic_font      Auto
bold_italic_font Auto
font_size        14.0

# Spacing (tight, archival)
adjust_line_height  4
adjust_column_width 0
window_padding_width 4

# Cursor
cursor_beam_thickness 7
cursor_underline_thickness 4.0

# No bell
enable_audio_bell no
visual_bell_duration 0.0

# Core
# background            #001419
# foreground            #9fabad
# cursor                #9fabad
# selection_background  #07667e
# selection_foreground  #9fabad

# ANSI Colors (Normal 0-7)
# color0  #00566b
# color1  #dc312e
# color2  #56a51d
# color3  #b28600
# color4  #1690f3
# color5  #d33682
# color6  #32aea2
# color7  #ede7d4

# ANSI Colors (Bright 8-15)
# color8  #07667e
# color9  #ca4c16
# color10 #9fabad
# color11 #647a82
# color12 #414cc8
# color13 #adb8b8
# color14 #adb8b8
# color15 #fdf6e2

# Cursor
# cursor #c0caf5
# cursor_text_color #1a1b26

# Selection highlight
# selection_foreground none
# selection_background #28344a

# The color for highlighting URLs on mouse-over
# url_color #9ece6a

# Window borders
# active_border_color #3d59a1
# inactive_border_color #101014
# bell_border_color #e0af68
# active_border_color #6f8f6f
# inactive_border_color #101410
# bell_border_color #6f8f6f


# UI
# active_border_color   #6f8f6f
# inactive_border_color #2a2f2b
# bell_border_color     #8a7f4f



# Transparency (very subtle)
background_opacity 0.97

# Performance / Old-school feel
repaint_delay 10
input_delay 0


# BEGIN_KITTY_THEME
# Kanagawa
include current-theme.conf
# END_KITTY_THEME
