# vim:ft=kitty

## name: Solarized Osaka
## author: craftzdog (colors extracted from solarized-osaka.nvim)
## blurb: Solarized Osaka color scheme for Kitty terminal

# Core
background            #001419
foreground            #9fabad
cursor                #9fabad
selection_background  #07667e
selection_foreground  #9fabad

# ANSI Colors (Normal 0-7)
color0  #00566b
color1  #dc312e
color2  #56a51d
color3  #b28600
color4  #1690f3
color5  #d33682
color6  #32aea2
color7  #ede7d4

# ANSI Colors (Bright 8-15)
color8  #07667e
color9  #ca4c16
color10 #9fabad
color11 #647a82
color12 #414cc8
color13 #adb8b8
color14 #adb8b8
color15 #fdf6e2
